apiVersion: v1
kind: Service
metadata:
  name: mlops-project1-service
  namespace: default
spec:
  selector:
    app: mlops-project1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer